Let's try a different action

diff --git a/.github/workflows/fetch-climacell.yml b/.github/workflows/fetch-climacell.yml
--- a/.github/workflows/fetch-climacell.yml
+++ b/.github/workflows/fetch-climacell.yml
@@ -1,28 +1,61 @@
-# This is a basic workflow to help you get started with Actions
+name: Fetch Climacell Forecast
 
-name: fetch-climacell
-
-# Controls when the action will run. 
 on:
-  # Triggers the workflow on push to the main branch
-  push:
-    branches: [ main ]
-
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
-
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
+  schedule:
+    - cron: 0 12 * * *
+    
 jobs:
-  # This workflow contains a single job called "build"
-  call-climacell-api:
-    # The type of runner that the job will run on
+  build:
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-    - name: save API
-      run:  curl --location --request GET 'https://data.climacell.co/v4/timelines?apikey=isddI3J554xIy57ZycsDOI2hkRCINvdM&timesteps=1h&location=39.99,-75.58&fields=temperature,humidity,dewPoint&units=imperial' > response.json
-    - uses: actions/upload-artifact@v2
-      with:
-        name: my-artifact
-        path: response.json
+      - uses: actions/checkout@v1
+      - name: Run a one-line script
+        run: pwd
+      - name: Run a multi-line script
+        run: |
+          ls
+          git status
+      - name: Save current weather condition
+        env:
+          CLIMACELL_API_KEY: ${{ secrets.CLIMACELL_API_KEY }}
+        run: |
+          FILE=./src/json/forecast.json
+          if [ -f "$FILE" ]; then
+              echo "$FILE exists. Done for today."
+          else
+              echo "Begin to get today's weather condition."
+              url="https://data.climacell.co/v4/timelines?apikey="$CLIMACELL_API_KEY$"&timesteps=1h&location=39.99,-75.58&fields=temperature,humidity,dewPoint&units=imperial"
+              response=$(curl -f "$url")
+              status=$?
+              if [ $status -eq 0 ]; then
+                  echo $response > $FILE
+                  echo "$FILE saved."
+              else
+                  echo "curl exit code: ($status) $response"
+                  exit $status
+              fi
+          fi
+      - name: git check in
+        env:
+          GIT_OWNER_EMAIL: ${{ secrets.GIT_OWNER_EMAIL }} 
+          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
+        run: |
+          git config user.email "$GIT_OWNER_EMAIL"
+          git config user.name "tikaro"
+          if [[ `git status --porcelain` ]]; then
+            git add .
+            git commit -a -m "add climacell forecast data"
+            git remote rm origin
+            git remote add origin https://tikaro:$PUSH_TOKEN@github.com/tikaro/sandex.git
+            git push origin HEAD:main
+          else
+            echo 'unable to detech changes'
+          fi
+
+
+
+
+
+
+      run:  curl --location --request GET '' > response.json
